AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template Deployment of a Thinkbox Deadline

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: VPC Information
          Parameters:
          - VPCId

        - Label:
            default: Storage Network Subnets
          Parameters:
          - PrivateStgSubnet1a
          - PrivateStgSubnet1b
          - PrivateStgSubnet1c

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: Select VPC
    ConstraintDescription: Must be an existing VPC in the selected region.

  PrivateStgSubnet1a:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateStgSubnet1b:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateStgSubnet1c:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

Resources:
  SecurityGroupsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/ec2-security-groups.yml'
      Parameters:
        VPCId: !Ref VPCId

  EFSFileSystemStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/efs-filesystem.yml'
      Parameters:
        PrivateStgSubnet1a: !Ref PrivateStgSubnet1a
        PrivateStgSubnet1b: !Ref PrivateStgSubnet1b
        PrivateStgSubnet1c: !Ref PrivateStgSubnet1c
        sgDeadlineEFSRepository: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineEFSRepository

Outputs:
  VPCId:
    Description: The VPC ID
    Value: !Ref VPCId
    Export:
      Name: !Sub "VPCId"

# Security Group Stack Outputs
  sgDeadlineRCS:
    Description: "Security Group ID for Deadline RCS Servers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineRCS
    Export:
      Name: !Sub "sgDeadlineRCS"

  sgDeadlineEFSRepository:
    Description: "Security Group ID for Deadline EFS Repository"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineEFSRepository
    Export:
      Name: !Sub "sgDeadlineEFSRepository"

  sgDeadlineDocumentDBCluster:
    Description: "Security Group ID for Deadline DocumentDB Cluster"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineDocumentDBCluster
    Export:
      Name: !Sub "sgDeadlineDocumentDBCluster"

  sgDeadlineLoadBalancers:
    Description: "Security Group ID for Deadline Application Loadbalancers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineLoadBalancers
    Export:
      Name: !Sub "sgDeadlineLoadBalancers"

  sgDeadlineWorkers:
    Description: "Security Group ID for Deadline Workers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineWorkers
    Export:
      Name: !Sub "sgDeadlineWorkers"