AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template Deployment of a Thinkbox Deadline

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: VPC Information
          Parameters:
          - VPCId

        - Label:
            default: Storage Network Subnets
          Parameters:
          - PrivateStgSubnet1a
          - PrivateStgSubnet1b
          - PrivateStgSubnet1c

        - Label:
            default: DB, Load Balancer & RCS Server Subnets
          Parameters:
          - PrivateSvcsSubnet1a
          - PrivateSvcsSubnet1b
          - PrivateSvcsSubnet1c

        - Label:
            default: Database Credentials
          Parameters:
          - DocumentDBUsername
          - DocumentDBPassword

        - Label:
            default: Deadline RCS Servers Configuration
          Parameters:
          - KeyName
          - DocumentDBPassword

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: Select VPC
    ConstraintDescription: Must be an existing VPC in the selected region.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access

  TopStackName:
    Type: String
    Description: Base logical name for this Deadline environment (e.g. studio-ldn-deadline)

# EFS Storage Parameters

  PrivateStgSubnet1a:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateStgSubnet1b:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateStgSubnet1c:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline Repository EFS Storage
    ConstraintDescription: Must be an existing subnet in the selected VPC.

# DocumentDB Parameters

  PrivateSvcsSubnet1a:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline DocumentDB Database
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateSvcsSubnet1b:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline DocumentDB Database
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  PrivateSvcsSubnet1c:
    Type: AWS::EC2::Subnet::Id
    Description: Select Subnet for the Deadline DocumentDB Database
    ConstraintDescription: Must be an existing subnet in the selected VPC.

  DocumentDBUsername:
    Description: "Enter the DocumentDB Username"
    Type: String
    NoEcho: false  # Set to true if you want to mask the input
    AllowedPattern: "^[a-zA-Z0-9_-]+$"
    ConstraintDescription: Specify an alphanumeric string that defines the login ID for the user, Username must start with a letter and contain 1 to 63 characters

  DocumentDBPassword:
    Description: "Enter the DocumentDB Username"
    Type: String
    NoEcho: true  # Set to true to mask the input
    MinLength: 8
    MaxLength: 32
    AllowedPattern: "^[a-zA-Z0-9]+$"
    ConstraintDescription: "Password must be at least eight characters long and cannot contain a / (slash), \" (double quote) or @ (at symbol)."

# Deadline RCS Servers Parameters

  RCSServerInstanceType:
    Type: String
    Default: t3a.medium
    AllowedValues:
      - t3a.medium
      - t3a.large
    Description: Instance type for Deadline RCS servers

Resources:
  SecurityGroupsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/ec2-security-groups.yml'
      Parameters:
        VPCId: !Ref VPCId

  IAMRolesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/iam.yml'
      Parameters:
        TopStackName: !Ref TopStackName

  EFSFileSystemStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/efs-filesystem.yml'
      Parameters:
        PrivateStgSubnet1a: !Ref PrivateStgSubnet1a
        PrivateStgSubnet1b: !Ref PrivateStgSubnet1b
        PrivateStgSubnet1c: !Ref PrivateStgSubnet1c
        sgDeadlineEFSRepository: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineEFSRepository
        TopStackName: !Ref TopStackName

  DocumentDBStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/documentdb-deadlinedb.yml'
      Parameters:
        VPCId: !Ref VPCId
        PrivateSvcsSubnet1a: !Ref PrivateSvcsSubnet1a
        PrivateSvcsSubnet1b: !Ref PrivateSvcsSubnet1b
        PrivateSvcsSubnet1c: !Ref PrivateSvcsSubnet1c
        sgDeadlineDocumentDBCluster: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineDocumentDBCluster
        DocumentDBUsername: !Ref DocumentDBUsername
        DocumentDBPassword: !Ref DocumentDBPassword

  PrivateLoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/private-loadbalancer.yml'
      Parameters:
        VPCId: !Ref VPCId
        PrivateSvcsSubnet1a: !Ref PrivateSvcsSubnet1a
        PrivateSvcsSubnet1b: !Ref PrivateSvcsSubnet1b
        PrivateSvcsSubnet1c: !Ref PrivateSvcsSubnet1c
        sgDeadlineLoadBalancers: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineLoadBalancers
        TopStackName: !Ref TopStackName

  RCSServerLaunchTemplateStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: 'https://danm-dev-cf-eu-west-2.s3.eu-west-1.amazonaws.com/aws-cfn-deadline/templates/rcs-server-launch-template.yml'
      Parameters:
        VPCId: !Ref VPCId
        PrivateSvcsSubnet1a: !Ref PrivateSvcsSubnet1a
        PrivateSvcsSubnet1b: !Ref PrivateSvcsSubnet1b
        PrivateSvcsSubnet1c: !Ref PrivateSvcsSubnet1c
        sgDeadlineWorkers: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineWorkers
        KeyName: !Ref KeyName
        RCSServerInstanceType: !Ref RCSServerInstanceType
        DeadlineRCSServerProfileArn: !GetAtt IAMRolesStack.Outputs.DeadlineRCSServerProfileArn

Outputs:
  VPCId:
    Description: The VPC ID
    Value: !Ref VPCId
    Export:
      Name: !Sub "VPCId"

# Security Group Stack Outputs
  sgDeadlineRCS:
    Description: "Security Group ID for Deadline RCS Servers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineRCS
    Export:
      Name: !Sub "sgDeadlineRCS"

  sgDeadlineEFSRepository:
    Description: "Security Group ID for Deadline EFS Repository"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineEFSRepository
    Export:
      Name: !Sub "sgDeadlineEFSRepository"

  sgDeadlineDocumentDBCluster:
    Description: "Security Group ID for Deadline DocumentDB Cluster"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineDocumentDBCluster
    Export:
      Name: !Sub "sgDeadlineDocumentDBCluster"

  sgDeadlineLoadBalancers:
    Description: "Security Group ID for Deadline Application Loadbalancers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineLoadBalancers
    Export:
      Name: !Sub "sgDeadlineLoadBalancers"

  sgDeadlineWorkers:
    Description: "Security Group ID for Deadline Workers"
    Value: !GetAtt SecurityGroupsStack.Outputs.sgDeadlineWorkers
    Export:
      Name: !Sub "sgDeadlineWorkers"

  EFSMountDNS:
    Description: "DNS name of the EFS mount target"
    Value: !GetAtt EFSFileSystemStack.Outputs.EFSMountDNS
    Export:
      Name: !Sub "EFSMountDNS"

  DeadlineRCSServerProfileArn:
    Description: "Instance Profile ARN for Deadline RCS Servers"
    Value: !GetAtt IAMRolesStack.Outputs.DeadlineRCSServerProfileArn
    Export:
      Name: !Sub "DeadlineRCSServerProfileArn"